# Generated by Django 4.1.3 on 2022-11-25 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=200)),
                ('costPrice', models.IntegerField(default=0)),
                ('sellingPrice', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('ingredientList', models.CharField(max_length=1000)),
                ('quantityList', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
