# Generated by Django 4.1.3 on 2022-11-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reserveInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredientName', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='costPrice',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bakeryitem',
            name='sellingPrice',
            field=models.FloatField(default=0),
        ),
    ]
