# Generated by Django 4.1.3 on 2022-11-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.CharField(max_length=32)),
                ('itemName', models.CharField(max_length=200)),
                ('quantity', models.FloatField(default=0)),
                ('sellingPrice', models.FloatField(default=0)),
                ('totalAmount', models.FloatField(default=0)),
            ],
        ),
    ]
