# Generated by Django 4.1.3 on 2022-11-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default='NA', max_length=50),
            preserve_default=False,
        ),
    ]
