# Generated by Django 4.1.3 on 2022-11-26 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='createdAt',
        ),
    ]
